--CON FOREIGN KEY
DROP TABLE SQL_SERVANT.Facturacion

DROP TABLE SQL_SERVANT.Facturacion_Pendiente

DROP TABLE SQL_SERVANT.Transferencia

DROP TABLE SQL_SERVANT.Cheque_Retiro

DROP TABLE SQL_SERVANT.Rol_Funcionalidad

DROP TABLE SQL_SERVANT.Usuario_Rol

DROP TABLE SQL_SERVANT.Usuario_Cliente

DROP TABLE SQL_SERVANT.Costo_Tipo_Cuenta

DROP TABLE SQL_SERVANT.Deposito

DROP TABLE SQL_SERVANT.Cliente_Cuenta

DROP TABLE SQL_SERVANT.Cuenta

DROP TABLE SQL_SERVANT.Cliente_Tarjeta

DROP TABLE SQL_SERVANT.Cliente_Datos

DROP TABLE SQL_SERVANT.Cliente

--SIN FOREIGN KEY
DROP TABLE SQL_SERVANT.Banco

DROP TABLE SQL_SERVANT.Pais

DROP TABLE SQL_SERVANT.Moneda

DROP TABLE SQL_SERVANT.Estado_Cuenta

DROP TABLE SQL_SERVANT.Tipo_Cuenta

DROP TABLE SQL_SERVANT.Funcionalidad

DROP TABLE SQL_SERVANT.Tarjeta

DROP TABLE SQL_SERVANT.Tipo_Identificacion

DROP TABLE SQL_SERVANT.Rol

DROP TABLE SQL_SERVANT.Usuario

DROP SCHEMA SQL_SERVANT