--CON FOREIGN KEY

DROP TABLE SQL_SERVANT.Rol_Funcionalidad

DROP TABLE SQL_SERVANT.Usuario_Rol

DROP TABLE SQL_SERVANT.Usuario_Cliente

--SIN FOREIGN KEY

DROP TABLE SQL_SERVANT.Funcionalidad

DROP TABLE SQL_SERVANT.Cliente

DROP TABLE SQL_SERVANT.Rol

DROP TABLE SQL_SERVANT.Usuario

DROP SCHEMA SQL_SERVANT