--PROCEDIMIENTOS
DROP PROCEDURE SQL_SERVANT.sp_login_check_valid_user

DROP PROCEDURE SQL_SERVANT.sp_password_check_ok

DROP PROCEDURE SQL_SERVANT.sp_password_change

DROP PROCEDURE SQL_SERVANT.sp_login_check_password

DROP PROCEDURE SQL_SERVANT.sp_rol_exist_one_by_user

DROP PROCEDURE SQL_SERVANT.sp_menu_list_functionality_by_user